### ISSUE TITLE
ERROR: protobuf/3.21.9 was not found in remote 'gitlab'

### ISSUE THREAD

**Issue by ranyev5** [wx9698/xviz#11]
when i run the command conan install xviz -- remote=gitlab 
ERROR: Failed requirement 'protobuf/3.21.9' from 'conanfile.py (xviz/0.1.0)'
ERROR: protobuf/3.21.9 was not found in remote 'gitlab'

**Comment by mjxu96** [comment]
Try
```bash
conan remote add gitlab https://gitlab.com/api/v4/projects/44861904/packages/conan
conan install xviz
```

without `--remote=gitlab`
