### ISSUE TITLE
message Values not start with 1

### ISSUE THREAD

**Issue by lancelot-Yagami** [wx9698/xviz#22]
![image](https://github.com/mjxu96/xviz/assets/99981182/a0447a57-034d-418b-a77a-fd95c6f1ea26)

**Comment by mjxu96** [comment]
These proto files are directly copied from https://github.com/aurora-opensource/xviz/blob/master/xviz/v2/core.proto#L108-L111

Will that starting from 2 cause any issue on any compiler/platform?

**Comment by lancelot-Yagami** [comment]
This may result in not being able to set multiple values, for example I want to set multiple values for doubles, because the conan used by the project now, which I am not familiar with, so it cannot be verified

**Comment by mjxu96** [comment]
Thanks, do you mind providing a minimum reproducer for this issue?

**Comment by lancelot-Yagami** [comment]
Sorry, it is my bad. I've found the problem.

I wanted the value of the stream to be of the following form in order to save space, and then I had a bit of a problem modifying the xviz code, but fortunately it has been solved, thanks :)


```
{
    "timestamp": 1317042272.349,
    "streams": [
        "/vehicle/velocity",
        "/vehicle/acceleration",
        "/vehicle/wheel_angle"
    ],
    "values": {
        "doubles": [
            3.5147680215,
            -0.3058103096,
            8.3440023763
        ]
    }
}
```

I will close the issue.
