### ISSUE TITLE
win10 support

### ISSUE THREAD

**Issue by 497711327** [wx9698/xviz#23]
这个window下能支持吗

**Comment by mjxu96** [comment]
yes if you use Conan.

**Comment by 497711327** [comment]
> yes if you use Conan.

When I install xviz, occur ERROR: Conanfile not found at C:\Users\jjs2hp\xviz

**Comment by mjxu96** [comment]
could you post your command and full output?

**Comment by 497711327** [comment]
PS C:\Users\jjs2hp> conan remote add gitlab https://gitlab.com/api/v4/projects/44861904/packages/conan
ERROR: Remote 'gitlab' already exists in remotes (use update to modify)
PS C:\Users\jjs2hp> conan install xviz
ERROR: Conanfile not found at C:\Users\jjs2hp\xviz
PS C:\Users\jjs2hp>

**Comment by mjxu96** [comment]
try `conan install -r gitlab xviz`?

**Comment by 497711327** [comment]
also this error : ERROR: Conanfile not found at C:\Users\jjs2hp\xviz

**Comment by mjxu96** [comment]
is there an xviz folder under C:\Users\jjs2hp\? Could you try after removing it?

**Comment by 497711327** [comment]
Not any xviz folder, I want to use your lib create a server, may be I can build from source code ?

**Comment by 497711327** [comment]
what cmake and conan version?

**Comment by mjxu96** [comment]
these are my versions on windows:
```
(base) PS C:\Users> conan --version
Conan version 1.55.0
(base) PS C:\Users> cmake --version
cmake version 3.22.6

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
