### ISSUE TITLE
Reuse

### ISSUE THREAD

**Issue by JunkyDeveloper** [wx9698/xviz#4]
I started at the same time also a cpp solution of xviz. But i write the whole framework with all builder to the current version 1.0.6 so can i use your solution to add protobuff or more to my solution? For forking it is to late because i have a complete other project structure. Currently it is a closed source but i want to publish it open source.

**Comment by mjxu96** [comment]
Hi,

Sure, no problem. This library is under the MIT license which means you can do whatever you want on my source codes as long as you credit me on my codes in your repo~~~

**Comment by JunkyDeveloper** [comment]
Thanks, after studing your code i can't directly use your solution but i will learn from your code how protobuff and the webserver will work. And i will also linking your project because you have a very short version my project is now large and will grow more in future.
Maybe in future you can also test my code because i will test it in a real car with ros and i saw you tested it virutal.

**Comment by mjxu96** [comment]
Sure, I definitely will try your codes. Thank you.
